# A simple example: Solve a system of linear equations

Here is an example of how to use the NAG Library to compute the solution of a real system of linear equations, $Ax = b$, where $A$ is an $n$ by $n$ matrix and $x$ and $b$ are $n$-vectors.

We import the `numpy` package - we will use it to create arrays.

In [1]:
import numpy as np

Create a 2D array to hold our input matrix A

In [2]:
a = np.array( [[1.80, 2.88, 2.05, -0.89],
               [5.25, -2.95, -0.95, -3.80],
               [1.58, -2.69, -2.90, -1.04],
               [-1.11, -0.66, -0.59, 0.80]])

And a 2D array to hold the right-hand side matrix - here we only use a single column

In [3]:
b = np.array( [[9.52], [24.35], [0.77], [-6.22]])

LAPACK is part of the NAG library, in the lapacklin chapter - import it now

In [4]:
from naginterfaces.library import lapacklin 

We use the dgesv function to solve our system of equations

In [5]:
_, ipiv, x = lapacklin.dgesv(a, b)

The pivot information used in the LU factorization is in output argument ipiv

In [6]:
print(ipiv)

[2 2 3 4]


And the solution is in x

In [7]:
print(x)

[[ 1.]
 [-1.]
 [ 3.]
 [-5.]]


Verify that the solution is correct by multiplying the input A by the output x

In [8]:
res=a@x          # The @ operator for matrix multiplication was introduced in later versions of numpy
print(res)       # Otherwise try the numpy.dot function: res=np.dot(a,x)

[[ 9.52]
 [24.35]
 [ 0.77]
 [-6.22]]


Compare the result with the input vector b

In [9]:
print(res-b)

[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-1.33226763e-15]
 [ 8.88178420e-16]]
