# A simple example: Solve a system of linear equations

Here is an example of how to use the NAG Library to compute the solution of a real system of linear equations, $Ax = b$, where $A$ is an $n$ by $n$ matrix and $x$ and $b$ are $n$-vectors. This variation of the simple example illustrates what happens when an error happens e.i. an exception is thrown due $b$ being of the wrong size.

We import the `numpy` package - we will use it to create arrays.

In [47]:
import numpy as np

Create a 2D array to hold our input matrix A, this matrix is rank deficient

In [48]:
a = np.array( [[1.80, 2.88, 2.05, -0.89],
               [5.25, -2.95, -0.95, -3.80],
               [1.58, -2.69, -2.90, -1.04],
               [-1.11, -0.66, -0.59, 0.80]])

And a 2D array to hold the right-hand side matrix - here we only use a single column

In [49]:
b = np.array( [[9.52], [24.35], [0.77], [-6.22]])
blen = b.size - 1

LAPACK is part of the NAG library, in the lapacklin chapter - import it now

In [50]:
from naginterfaces.library import lapacklin

We use the `dgesv` function to solve our system of equations. Executing the next command will throw the `NagShapeError` exception informing that the system could not be solved. Additionally, it tells us that the reason for failing is because the matrix $A$ is of the wrong size, it should be of size 3 by 3.

We wrap the function with a `try` statement and `catch` the exception so we can gracefully handle the error 

In [51]:
from naginterfaces.base import utils
try:
    _, ipiv, x = lapacklin.dgesv(a, b[:blen])
except utils.NagShapeError as e:
    print('System of linear equations could not be solved! Reason:\n{}'.format(e.msg))
    print('Either extend vector b or reduce matrix A.')
    # Fix the problem by providing the full lenght of vector b to the function:
    blen = b.size

_, ipiv, x = lapacklin.dgesv(a, b[:blen])

System of linear equations could not be solved! Reason:
has shape (4, 4), but must have shape (3, 3)
Either extend vector b or reduce matrix A.


The pivot information used in the LU factorization is in output argument ipiv

In [52]:
print(ipiv)

[2 2 3 4]


And the solution is in x

In [53]:
print(x)

[[ 1.]
 [-1.]
 [ 3.]
 [-5.]]


Verify that the solution is correct by multiplying the input A by the output x

In [54]:
res=a@x          # The @ operator for matrix multiplication was introduced in later versions of numpy
print(res)       # Otherwise try the numpy.dot function: res=np.dot(a,x)

[[ 9.52]
 [24.35]
 [ 0.77]
 [-6.22]]


Compare the result with the input vector b

In [55]:
print(res-b)

[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-1.33226763e-15]
 [ 8.88178420e-16]]
